spring:
  application:
    name: "pricing"

management:
  tracing:
    sampling:
      probability: 1
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "${JAEGER_ENDPOINT:http://localhost:4318/v1/traces}"
